export const COMMERCIAL_HIGH_PATTERNS = [
  "book now",
  "book your",
  "schedule your",
  "schedule a consultation",
  "contact us",
  "call today",
  "call now",
  "free consultation",
  "shop now",
  "buy now",
  "add to cart",
  "promo code",
  "discount code",
  "limited offer",
  "special offer",
  "free shipping",
  "price list",
  "appointment today",
  "link in bio",
  "affiliate link",
  "dm us",
  "visit our clinic",
];

export const COMMERCIAL_MODERATE_PATTERNS = [
  "available now",
  "introducing",
  "now available",
  "launches",
  "announces",
  "our product",
  "our treatment",
  "our technology",
  "our solution",
  "visit our",
  "learn more",
  "now offering",
  "new service",
];

export const COMMERCIAL_SPONSORSHIP_PATTERNS = [
  "sponsored",
  "paid partnership",
  "partnered with",
  "in collaboration with",
  "gifted by",
  "gifted to me",
  "ad:",
  "#ad",
  "#sponsored",
  "affiliate",
  "use my code",
];

export const FIRST_PERSON_PATTERNS = [
  " i ",
  " i'm ",
  " i’m ",
  " i've ",
  " i’ve ",
  " i'd ",
  " i’d ",
  " my ",
  " me ",
  " myself ",
  " we ",
  " our ",
];

export const PATIENT_IDENTITY_PATTERNS = [
  "as a patient",
  "my diagnosis",
  "my symptoms",
  "my condition",
  "my treatment",
  "my doctor",
  "my results",
  "my recovery",
  "my procedure",
  "my appointment",
];

export const LIVED_EXPERIENCE_PATTERNS = [
  "i received",
  "i underwent",
  "i tried",
  "i started",
  "i stopped",
  "i switched",
  "i chose",
  "i decided",
  "i experienced",
  "i noticed",
  "i felt",
  "i had",
  "i got treated",
  "worked for me",
  "did not work for me",
  "didn't work for me",
  "my recovery",
  "my side effects",
  "my results",
  "my experience",
  "my treatment",
  "my procedure",
  "after treatment",
  "after the treatment",
  "after my treatment",
  "before treatment",
  "before the treatment",
  "before my treatment",
  "weeks later",
  "months later",
  "day after",
  "days after",
];

export const TREATMENT_DISCUSSION_PATTERNS = [
  "treatment",
  "procedure",
  "injection",
  "injectable",
  "therapy",
  "results",
  "side effect",
  "side effects",
  "recovery",
  "swelling",
  "bruising",
  "pain",
  "improvement",
  "outcome",
  "consultation",
  "appointment",
  "doctor",
  "dermatologist",
  "injector",
  "provider",
  "clinic",
  "dose",
  "session",
];

export const COMMUNITY_DISCUSSION_PATTERNS = [
  "has anyone",
  "anyone tried",
  "anyone else",
  "what do you think",
  "thoughts on",
  "does anyone know",
  "looking for advice",
  "need advice",
  "would you recommend",
  "is this normal",
  "how long did",
  "how long does",
  "what was your experience",
  "what are your experiences",
  "can anyone share",
  "curious about",
  "considering",
  "thinking about",
  "wondering if",
  "should i",
  "worth it",
  "pros and cons",
  "before and after",
  "results?",
  "experience?",
];

export const CAREGIVER_PATTERNS = [
  "as a caregiver",
  "caring for",
  "my child",
  "my son",
  "my daughter",
  "my husband",
  "my wife",
  "my mother",
  "my father",
  "my partner",
  "our family",
];

export const PROVIDER_IDENTITY_PATTERNS = [
  "as a physician",
  "as a doctor",
  "as a clinician",
  "as a dermatologist",
  "as a surgeon",
  "as a nurse",
  "as an injector",
  "as a provider",
  "in my practice",
  "in our practice",
  "in my clinic",
  "in our clinic",
  "my clinical practice",
  "board-certified",
  "board certified",
];

export const PROVIDER_CLINICAL_PATTERNS = [
  "my patients",
  "our patients",
  "patient selection",
  "treatment planning",
  "clinical experience",
  "during consultation",
  "in consultation",
  "i recommend",
  "we recommend",
  "we assess",
  "i assess",
  "we treat",
  "i treat",
  "patient outcomes",
  "clinical outcomes",
  "contraindications",
  "treatment protocol",
  "clinical protocol",
  "patient safety",
];

export const JOURNALIST_PATTERNS = [
  "according to",
  "experts say",
  "reported that",
  "the company said",
  "in an interview",
  "the study found",
  "researchers found",
  "a spokesperson said",
  "the publication reported",
  "the report found",
];

export const PRESS_RELEASE_PATTERNS = [
  "press release",
  "media contact",
  "pr newswire",
  "prnewswire",
  "business wire",
  "businesswire",
  "globe newswire",
  "forward-looking statements",
  "investor relations",
  "announced today",
];

export const RESEARCH_LANGUAGE_PATTERNS = [
  "peer-reviewed",
  "peer reviewed",
  "randomized",
  "controlled trial",
  "clinical trial",
  "systematic review",
  "meta-analysis",
  "doi:",
  "pmid:",
  "methods:",
  "results:",
  "conclusion:",
  "study participants",
];

export const RESEARCH_CLAIM_PATTERNS = [
  "clinical evidence",
  "research shows",
  "research proves",
  "study shows",
  "scientifically proven",
  "clinically proven",
];

export const ADVOCACY_PATTERNS = [
  "patient advocacy",
  "patient organization",
  "patient organisation",
  "support group",
  "advocacy organization",
  "advocacy organisation",
  "patient community",
];

export const INFLUENCER_PATTERNS = [
  "follow me",
  "subscribe",
  "use my code",
  "affiliate",
  "my followers",
  "content creator",
  "influencer",
  "unboxing",
  "haul",
  "link in bio",
  "gifted",
  "brand partner",
  "paid partnership",
];

export const SOCIAL_PROMOTIONAL_PATTERNS = [
  "book now",
  "schedule now",
  "contact us",
  "call us",
  "dm us",
  "visit us",
  "now offering",
  "limited availability",
  "special pricing",
  "special offer",
  "free consultation",
  "our clinic",
  "our medspa",
  "our practice",
  "our services",
  "our patients love",
  "before and after available",
];