import { RankingProfile } from "../types";

export const regenerativeAestheticsRankingProfile: RankingProfile = {
  profileId: "regenerative_aesthetics",

  globalBoosts: [
    { term: "regenerative aesthetics", weight: 8 },
    { term: "regenerative medicine", weight: 7 },
    { term: "regenerative biology", weight: 8 },
    { term: "medical aesthetics", weight: 5 },
    { term: "aesthetic medicine", weight: 5 },
    { term: "skin quality", weight: 6 },
    { term: "natural-looking results", weight: 7 },
    { term: "natural results", weight: 6 },
    { term: "tissue regeneration", weight: 6 },
    { term: "collagen stimulation", weight: 6 },
    { term: "biostimulation", weight: 7 },
    { term: "biostimulator", weight: 6 },
    { term: "preventative aesthetics", weight: 7 },
    { term: "preventative treatments", weight: 6 },
    { term: "younger demographic", weight: 6 },
    { term: "skin quality over volume", weight: 8 },
    { term: "sculptra", weight: 5 },
    { term: "radiesse", weight: 5 },
    { term: "prp", weight: 4 },
    { term: "prf", weight: 4 },
    { term: "polynucleotide", weight: 4 },
    { term: "pdrn treatment", weight: 4 },
  ],

  globalPenalties: [
    { term: "moisturizer", weight: 75 },
    { term: "cleanser", weight: 75 },
    { term: "lip oil", weight: 75 },
    { term: "lip mask", weight: 75 },
    { term: "capsule cream", weight: 75 },
    { term: "gel mask", weight: 75 },
    { term: "skincare haul", weight: 75 },
    { term: "sephora", weight: 75 },
    { term: "amazon", weight: 75 },
    { term: "shop now", weight: 100 },
    { term: "link in bio", weight: 100 },
    { term: "affiliate", weight: 100 },
    { term: "special offer", weight: 150 },
    { term: "anniversary offer", weight: 150 },
    { term: "free consultation", weight: 150 },
    { term: "price list", weight: 150 },
    { term: "press release", weight: 100 },
    { term: "media contact", weight: 100 },
    { term: "investor", weight: 100 },
    { term: "shareholder", weight: 100 },
    { term: "market report", weight: 100 },
    { term: "restructuring plans", weight: 100 },
    { term: "intellectual property portfolio", weight: 100 },
    { term: "skin longevity explained", weight: 75 },
    { term: "gut microbiome", weight: 75 },
    { term: "marine collagen", weight: 75 },
  ],

  globalHardRejectTerms: [
    "call:",
    "phone:",
    "whatsapp",
    "map:",
    "address:",
    "book now",
    "contact us",
    "visit us",
    "special anniversary offer",
    "promo code",
    "clinic hotline",
    "clinic located",
    "sephora haul",
    "shopwithme",
    "prnewswire",
    "business wire",
    "globe newswire",
    "quarterly revenue",
    "nasdaq",
    "global ambassador",
    "brand ambassador",
    "korea's best barber",
    "haircut",
    "male makeup",
  ],

  intentRules: {
    market_interest: {
      preferredFindingTypes: [
        "market_interest",
        "adoption_driver",
      ],
      boosts: [
        { term: "younger consumers", weight: 10 },
        { term: "entering aesthetic clinics earlier", weight: 12 },
        { term: "skin quality over volume", weight: 12 },
        { term: "reduced reliance on high-volume injectables", weight: 10 },
        { term: "natural-looking results", weight: 10 },
        { term: "collagen stimulation", weight: 10 },
        { term: "regenerative biology", weight: 10 },
        { term: "tissue health", weight: 8 },
      ],
    },

    education_barriers: {
      preferredFindingTypes: [
        "education_barrier",
        "market_interest",
      ],
      boosts: [
        { term: "what is pdrn", weight: 8 },
        { term: "what are exosomes", weight: 8 },
        { term: "skeptical", weight: 6 },
        { term: "hype", weight: 6 },
        { term: "unsafe", weight: 6 },
        { term: "confusing", weight: 6 },
      ],
    },

    competitive_alternatives: {
      preferredFindingTypes: [
        "competitive_alternative",
        "treatment_concern",
      ],
      boosts: [
        { term: "botox", weight: 5 },
        { term: "filler", weight: 5 },
        { term: "laser", weight: 5 },
        { term: "microneedling", weight: 5 },
        { term: "facelift", weight: 5 },
        { term: "instead of filler", weight: 8 },
      ],
    },

    adoption_drivers: {
      preferredFindingTypes: [
        "adoption_driver",
        "market_interest",
      ],
      boosts: [
        { term: "natural results", weight: 8 },
        { term: "minimal downtime", weight: 8 },
        { term: "long-lasting", weight: 7 },
        { term: "collagen", weight: 6 },
        { term: "skin quality", weight: 6 },
      ],
    },

    market_opportunities: {
      preferredFindingTypes: [
        "market_opportunity",
        "market_interest",
        "adoption_driver",
        "education_barrier",
      ],
      boosts: [
        { term: "education gap", weight: 8 },
        { term: "provider trust", weight: 7 },
        { term: "younger demographic", weight: 7 },
        { term: "preventative", weight: 7 },
        { term: "natural-looking", weight: 7 },
      ],
    },
  },
};