export const ONTOLOGY_PATTERNS = {
  patientIdentity: [
    "as a patient",
    "my diagnosis",
    "my symptoms",
    "my condition",
    "my treatment",
    "my procedure",
    "my doctor",
    "my dermatologist",
    "my injector",
    "my results",
    "my recovery",
    "my side effects",
  ],

  caregiverIdentity: [
    "as a caregiver",
    "my child",
    "my son",
    "my daughter",
    "my husband",
    "my wife",
    "my partner",
    "my mother",
    "my father",
    "caring for",
    "our family",
  ],

  providerIdentity: [
    "as a physician",
    "as a doctor",
    "as a dermatologist",
    "as a clinician",
    "as a nurse",
    "as an injector",
    "as a provider",
    "in my practice",
    "in our practice",
    "in my clinic",
    "in our clinic",
    "board-certified",
    "board certified",
    "medical director",
    "plastic surgeon",
    "nurse practitioner",
  ],

  providerLanguage: [
    "my patients",
    "our patients",
    "patient selection",
    "treatment planning",
    "clinical experience",
    "clinical outcomes",
    "patient outcomes",
    "patient safety",
    "contraindications",
    "treatment protocol",
    "clinical protocol",
    "in consultation",
    "during consultation",
    "we recommend",
    "i recommend",
    "we assess",
    "i assess",
    "we treat",
    "i treat",
    "anatomy-based",
    "anatomy based",
  ],

  researcherIdentity: [
    "our research",
    "our study",
    "we investigated",
    "we evaluated",
    "the researchers",
    "research team",
    "principal investigator",
    "study authors",
  ],

  journalistLanguage: [
    "according to",
    "experts say",
    "reported that",
    "the company said",
    "a spokesperson said",
    "in an interview",
    "the article",
    "the report found",
    "the publication reported",
  ],

  communityQuestion: [
    "has anyone",
    "anyone tried",
    "anyone else",
    "does anyone",
    "what do you think",
    "thoughts on",
    "looking for advice",
    "need advice",
    "would you recommend",
    "is this normal",
    "what was your experience",
    "can anyone share",
    "curious about",
    "considering",
    "thinking about",
    "wondering if",
    "should i",
    "worth it",
    "pros and cons",
  ],

  personalExperience: [
    "i tried",
    "i received",
    "i underwent",
    "i started",
    "i stopped",
    "i switched",
    "i chose",
    "i decided",
    "i experienced",
    "i noticed",
    "i felt",
    "i had",
    "i got",
    "worked for me",
    "did not work for me",
    "didn't work for me",
    "my experience",
    "my results",
    "my recovery",
    "my side effects",
    "after my treatment",
    "after treatment",
    "weeks later",
    "months later",
  ],

  testimonial: [
    "i love",
    "my favorite",
    "must-have",
    "must have",
    "worked wonders",
    "amazing results",
    "changed my skin",
    "highly recommend",
    "can’t recommend",
    "can't recommend",
    "best treatment",
    "best product",
  ],

  recommendation: [
    "my skincare favorites",
    "my skincare must haves",
    "my skincare must-haves",
    "my favorite products",
    "products i love",
    "treatments i love",
    "highly recommend",
    "recommend this",
    "worth trying",
    "worth it",
    "before and after",
  ],

  providerEducation: [
    "what is",
    "how it works",
    "works by",
    "treatment works",
    "patient selection",
    "treatment planning",
    "clinical benefits",
    "clinical outcomes",
    "collagen stimulation",
    "stimulates collagen",
    "fda-approved",
    "fda approved",
    "anatomy",
    "contraindication",
    "treatment protocol",
    "in clinical practice",
  ],

  patientEducation: [
    "what to expect",
    "before treatment",
    "after treatment",
    "recovery time",
    "downtime",
    "side effects",
    "benefits include",
    "common myths",
    "frequently asked",
    "things to know",
    "explained",
    "everything you need to know",
  ],

  researchDissemination: [
    "peer-reviewed",
    "peer reviewed",
    "randomized",
    "clinical trial",
    "study found",
    "study shows",
    "research found",
    "research shows",
    "publication",
    "journal",
    "doi",
    "pmid",
    "methods",
    "results",
    "conclusion",
    "scientific investigation",
  ],

  clinicPromotion: [
    "book now",
    "schedule now",
    "schedule your",
    "book your",
    "contact us",
    "call us",
    "dm us",
    "free consultation",
    "our clinic",
    "our medspa",
    "our practice",
    "now offering",
    "appointments available",
    "visit our clinic",
    "treatment at",
    "best skin clinic",
    "cost",
    "pricing",
  ],

  productPromotion: [
    "shop now",
    "buy now",
    "add to cart",
    "our product",
    "our serum",
    "our moisturizer",
    "our formula",
    "ingredients",
    "free shipping",
    "promo code",
    "discount code",
    "available now",
    "product benefits",
    "link in bio",
  ],

  brandAnnouncement: [
    "we are excited",
    "we're excited",
    "we are pleased",
    "announced today",
    "introducing",
    "launching",
    "launches",
    "new innovation",
    "new platform",
    "new product",
    "our latest",
    "proud to announce",
    "pleased to announce",
  ],

  eventPromotion: [
    "join us",
    "see you there",
    "upcoming event",
    "register now",
    "conference",
    "summit",
    "webinar",
    "speaking at",
    "presenting at",
    "attended the",
    "event dedicated to",
    "session",
    "symposium",
    "masterclass",
  ],

  eventRecap: [
    "great to attend",
    "pleased to attend",
    "we attended",
    "highlights from",
    "recap from",
    "takeaways from",
    "what we learned at",
    "thank you to everyone",
    "great conversations at",
  ],

  thoughtLeadership: [
    "my perspective",
    "our perspective",
    "industry perspective",
    "in my experience",
    "what leaders should know",
    "key considerations",
    "important considerations",
    "the future of",
    "where the industry is going",
    "what this means",
  ],

  influencer: [
    "paid partnership",
    "sponsored",
    "#ad",
    "#sponsored",
    "gifted",
    "gifted by",
    "use my code",
    "affiliate",
    "link in bio",
    "follow me",
    "subscribe",
    "brand partner",
    "my followers",
    "content creator",
    "celebs",
    "celebrity",
  ],

  advocacy: [
    "patient advocacy",
    "patient organization",
    "patient organisation",
    "advocacy organization",
    "advocacy organisation",
    "support group",
    "patient community",
    "awareness campaign",
    "patient resources",
  ],

  clinicAccount: [
    "clinic",
    "medspa",
    "med spa",
    "medical spa",
    "aesthetics clinic",
    "aesthetic clinic",
    "dermatology",
    "plastic surgery",
    "cosmetic surgery",
    "skin clinic",
    "laser clinic",
  ],

  providerCredential: [
    "md",
    "m.d.",
    "do",
    "d.o.",
    "mbbs",
    "phd",
    "ph.d.",
    "rn",
    "r.n.",
    "np",
    "pa-c",
    "dermatologist",
    "physician",
    "doctor",
    "surgeon",
    "nurse",
    "injector",
    "clinician",
    "medical director",
    "board-certified",
    "board certified",
  ],

  brandAccount: [
    "official",
    "inc.",
    "llc",
    "ltd",
    "limited",
    "company",
    "global",
    "laboratories",
    "labs",
    "pharmaceutical",
    "pharma",
    "biotech",
  ],
} as const;