create extension if not exists pgcrypto;

create table if not exists public.therapeutic_areas (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.user_therapeutic_access (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null,
  therapeutic_area text not null,
  created_at timestamptz not null default now(),
  unique (clerk_user_id, therapeutic_area)
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  therapeutic_area text not null,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_pinned boolean not null default false
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null,
  content jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.curated_insights (
  id uuid primary key default gen_random_uuid(),
  therapeutic_area text not null,
  source_name text,
  source_type text,
  source_date date,
  insight_type text not null,
  title text not null,
  summary text,
  detail text,
  evidence_excerpt text,
  country text,
  region text,
  persona text,
  platform text,
  audience text,
  journey_stage text,
  topic text,
  tags jsonb not null default '[]',
  metadata jsonb not null default '{}',
  confidence numeric,
  importance numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.curated_themes (
  id uuid primary key default gen_random_uuid(),
  therapeutic_area text not null,
  quarter text,
  theme_name text not null,
  theme_description text not null,
  report_excerpt text,
  report_section text,
  created_at timestamptz not null default now()
);

create table if not exists public.live_themes (
  id uuid primary key default gen_random_uuid(),
  therapeutic_area text not null,
  quarter text,
  source_type text not null,
  theme_name text not null,
  theme_description text not null,
  mention_count integer not null default 0,
  engagement_sum numeric not null default 0,
  confidence numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.theme_matches (
  id uuid primary key default gen_random_uuid(),
  therapeutic_area text not null,
  quarter text,
  live_theme_name text not null,
  curated_theme_name text,
  relationship text not null,
  similarity_score numeric not null default 0,
  rationale text,
  confidence numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists therapeutic_areas_active_sort_idx
  on public.therapeutic_areas (is_active, sort_order, name);
create index if not exists user_therapeutic_access_user_idx
  on public.user_therapeutic_access (clerk_user_id, therapeutic_area);
create index if not exists chat_sessions_user_updated_idx
  on public.chat_sessions (user_id, updated_at desc);
create index if not exists chat_messages_session_created_idx
  on public.chat_messages (session_id, created_at);
create index if not exists curated_insights_area_idx
  on public.curated_insights (therapeutic_area, created_at desc);
create index if not exists curated_themes_area_idx
  on public.curated_themes (therapeutic_area, created_at desc);
create index if not exists live_themes_area_idx
  on public.live_themes (therapeutic_area, created_at desc);
create index if not exists theme_matches_area_idx
  on public.theme_matches (therapeutic_area, created_at desc);

alter table public.therapeutic_areas enable row level security;
alter table public.user_therapeutic_access enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.curated_insights enable row level security;
alter table public.curated_themes enable row level security;
alter table public.live_themes enable row level security;
alter table public.theme_matches enable row level security;

comment on table public.therapeutic_areas is
  'Application therapeutic-area registry used by server-mediated AskSocial access controls.';
comment on table public.user_therapeutic_access is
  'Per-user therapeutic-area access grants keyed by Clerk user ID.';
