import { DiseaseProfile } from "./types";

export const botulinumToxinProfile: DiseaseProfile = {
  profileId: "botulinum_toxin",
  therapeuticArea: "Botulinum toxin",
  diseaseNames: [
    "botulinum toxin", "botulinum toxin type a", "botulinum neurotoxin", "bont-a", "bonta",
    "neuromodulator", "neurotoxin injection", "tox treatment", "botox", "dysport", "xeomin",
    "jeuveau", "daxxify", "letibotulinumtoxin", "onabotulinumtoxin", "abobotulinumtoxin",
    "incobotulinumtoxin", "prabotulinumtoxin", "daxibotulinumtoxin",
  ],
  symptomPatterns: {
    "dynamic lines and wrinkles": ["forehead lines", "frown lines", "glabellar lines", "crow's feet", "crows feet", "bunny lines", "wrinkles"],
    "facial balance": ["brow lift", "lip flip", "gummy smile", "masseter", "jaw slimming", "platysmal bands", "neck bands"],
    "duration concerns": ["wearing off", "wore off", "didn't last", "did not last", "how long does botox last", "short duration", "long lasting"],
    "undesired aesthetic outcomes": ["frozen face", "heavy brow", "droopy eyelid", "eyelid ptosis", "spock brow", "asymmetry", "uneven smile"],
    "treatment reactions": ["headache", "bruising", "swelling", "pain after", "difficulty swallowing", "dysphagia", "muscle weakness", "vision changes", "allergic reaction"],
    "therapeutic indications": ["chronic migraine", "hyperhidrosis", "excessive sweating", "cervical dystonia", "spasticity", "overactive bladder", "blepharospasm"],
  },
  treatmentPatterns: {
    "onabotulinumtoxinA": ["botox", "onabotulinumtoxina", "onabotulinumtoxin a"],
    "abobotulinumtoxinA": ["dysport", "abobotulinumtoxina", "abobotulinumtoxin a"],
    "incobotulinumtoxinA": ["xeomin", "incobotulinumtoxina", "incobotulinumtoxin a"],
    "prabotulinumtoxinA": ["jeuveau", "nuceiva", "prabotulinumtoxina", "prabotulinumtoxin a"],
    "daxibotulinumtoxinA": ["daxxify", "daxibotulinumtoxina", "daxibotulinumtoxin a"],
    "letibotulinumtoxinA": ["letybo", "letibotulinumtoxina", "letibotulinumtoxin a"],
    "botulinum toxin procedures": ["neuromodulator", "neurotoxin", "tox treatment", "microbotox", "microtox", "baby botox", "preventative botox"],
  },
  burdenTerms: [
    "regret", "anxiety", "worried", "scared", "unsafe", "side effect", "complication", "botched",
    "frozen", "unnatural", "pain", "bruising", "swelling", "ptosis", "weakness", "dysphagia",
    "expensive", "cost", "wearing off", "didn't work", "resistance", "antibodies", "counterfeit",
  ],
  patientIndicators: [
    "i got botox", "i had botox", "my botox", "i tried dysport", "i tried xeomin", "my injector",
    "my forehead", "my crow's feet", "my crows feet", "my migraine", "i'm considering", "i am considering",
    "has anyone", "should i", "is it normal", "after my injections", "my results", "wore off",
  ],
  caregiverIndicators: ["my partner", "my spouse", "my child", "my mother", "my father", "caregiver"],
  educationalExclusionPatterns: ["training course", "certification course", "masterclass", "injector academy"],
  lowQualityNoisePatterns: ["book now", "limited offer", "discount code", "dm to book", "call today", "price list"],
  hardExclusionPatterns: ["now hiring", "job opening", "botox training model", "injector training models needed"],
  requirePatientVoice: false,
  requireDiseaseContextForSymptoms: false,
  brands: ["Botox", "Dysport", "Xeomin", "Jeuveau", "Nuceiva", "Daxxify", "Letybo"],
  procedures: [
    "Glabellar line treatment", "Forehead line treatment", "Crow's feet treatment", "Brow lift", "Lip flip",
    "Masseter treatment", "Gummy smile treatment", "Platysmal band treatment", "Chronic migraine treatment",
    "Hyperhidrosis treatment", "Spasticity treatment", "Cervical dystonia treatment",
  ],
  journeyStages: ["Awareness", "Considering Treatment", "Provider Selection", "Consultation", "Treatment", "Early Recovery", "Results", "Maintenance", "Switching", "Complication"],
  emotions: ["Trust", "Fear", "Hope", "Regret", "Confusion", "Excitement", "Confidence", "Anxiety", "Frustration", "Skepticism"],
  knowledgeDomains: [
    { id: "natural-expression", name: "Natural Expression", type: "Experience Theme", description: "Preference for movement-preserving, subtle results.", signalPhrases: ["still have movement", "not frozen", "natural result", "subtle botox", "softened lines"], keywords: ["baby botox", "microbotox", "microtox", "conservative dosing"] },
    { id: "duration-maintenance", name: "Duration & Maintenance", type: "Treatment Theme", description: "How long benefits last and how often people return.", signalPhrases: ["wearing off", "wore off", "how long does it last", "lasted only"], keywords: ["duration", "maintenance", "touch up", "three months", "six months"] },
    { id: "safety-adverse-events", name: "Safety & Adverse Events", type: "Safety Theme", description: "Reported side effects, complications, and risk questions requiring evidence-qualified review.", signalPhrases: ["after botox", "side effect", "is this normal", "went wrong"], keywords: ["ptosis", "droopy eyelid", "dysphagia", "weakness", "headache", "asymmetry", "counterfeit"] },
    { id: "brand-switching", name: "Brand Choice & Switching", type: "Competitive Theme", description: "Comparisons and switching among toxin formulations.", signalPhrases: ["switched from botox", "botox vs dysport", "xeomin vs botox", "which tox"], keywords: ["botox", "dysport", "xeomin", "jeuveau", "daxxify", "letybo", "nuceiva"] },
    { id: "provider-trust", name: "Provider Trust & Technique", type: "Care Delivery Theme", description: "The role of injector credentials, anatomy, dosing, placement, and consultation.", signalPhrases: ["trust my injector", "experienced injector", "board certified", "who injects"], keywords: ["injector", "dermatologist", "plastic surgeon", "provider", "units", "placement", "technique"] },
    { id: "access-value", name: "Access & Value", type: "Access Theme", description: "Affordability, unit pricing, availability, and treatment value.", signalPhrases: ["worth the cost", "too expensive", "price per unit", "can't afford"], keywords: ["cost", "price", "units", "insurance", "access", "maintenance cost"] },
    { id: "therapeutic-use", name: "Therapeutic Use", type: "Medical Theme", description: "Experience with recognized and emerging non-aesthetic indications.", signalPhrases: ["for my migraines", "for sweating", "for spasticity", "for dystonia"], keywords: ["migraine", "hyperhidrosis", "spasticity", "dystonia", "overactive bladder", "blepharospasm"] },
  ],
  adverseEventPatterns: {
    ptosis: ["ptosis", "droopy eyelid", "heavy eyelid"],
    dysphagia: ["dysphagia", "difficulty swallowing", "trouble swallowing"],
    weakness: ["muscle weakness", "generalized weakness"],
    asymmetry: ["asymmetry", "uneven smile", "spock brow"],
    headache: ["headache", "migraine after"],
  },
  marketThemes: ["Natural expression", "Duration and maintenance", "Safety and adverse events", "Brand switching", "Provider trust", "Access and value", "Therapeutic use"],
};
