import { DiseaseProfile } from "./types";

export const regenerativeAestheticsProfile: DiseaseProfile = {
  profileId: "regenerative_aesthetics",
  therapeuticArea: "regenerative_aesthetics",

  diseaseNames: [
    "regenerative aesthetics",
    "regenerative aesthetic",
    "regenerative medicine aesthetics",
    "aesthetic regenerative medicine",
    "regenerative esthetics",
    "regenerative skin",
    "skin regeneration",
    "skin regenerative",
    "collagen regeneration",
    "collagen stimulation",
    "collagen-stimulating",
    "tissue regeneration",
    "biostimulation",
    "biostimulator",
    "biostimulators",
    "bio-stimulation",
    "bio stimulator",
    "skin rejuvenation",
    "facial rejuvenation",
    "non-surgical rejuvenation",
    "natural rejuvenation",
    "anti-aging",
    "anti aging",
    "well aging",
    "skin longevity",
    "longevity aesthetics",
    "longevity skincare",
    "regenerative skincare",
    "exosome facial",
    "exosome skincare",
    "exosome skin booster",
    "exosomes for skin",
    "stem cell facial",
    "stem cell skincare",
    "stem cell skin",
    "stem cell therapy for skin",
    "prp facial",
    "prp skin",
    "prp hair",
    "prf facial",
    "prf skin",
    "platelet-rich plasma facial",
    "platelet rich plasma facial",
    "platelet-rich fibrin facial",
    "platelet rich fibrin facial",
    "polynucleotides",
    "polynucleotide",
    "pdrn",
    "salmon sperm facial",
    "salmon dna",
    "rejuran",
    "juvelook",
    "skinvive",
    "sculptra",
    "radiesse",
    "growth factors",
    "collagen induction",
    "skin boosters",
    "skin booster",
    "bio-remodeling",
    "bioremodeling",
    "profhilo",
    "microneedling with exosomes",
    "microneedling with prp",
    "microneedling with prf",
  ],

  symptomPatterns: {
    aging_signs: [
      "aging",
      "ageing",
      "fine lines",
      "wrinkles",
      "crepey skin",
      "skin laxity",
      "sagging",
      "loss of elasticity",
      "loss of collagen",
      "volume loss",
      "mature skin",
    ],
    skin_texture: [
      "texture",
      "rough skin",
      "uneven texture",
      "pores",
      "large pores",
      "acne scars",
      "acne scarring",
      "scarring",
      "smooth skin",
      "skin smoothness",
    ],
    pigmentation: [
      "pigmentation",
      "hyperpigmentation",
      "dark spots",
      "sun spots",
      "melasma",
      "uneven tone",
      "tone",
      "brightening",
      "dullness",
    ],
    inflammation_redness: [
      "redness",
      "inflammation",
      "rosacea",
      "irritation",
      "sensitive skin",
      "barrier repair",
      "skin barrier",
    ],
    dryness_dullness: [
      "dry skin",
      "dehydrated skin",
      "dull skin",
      "glow",
      "glowy",
      "dewy",
      "radiance",
      "hydration",
      "skin quality",
      "glass skin",
    ],
    hair_loss: [
      "hair loss",
      "thinning hair",
      "hair thinning",
      "alopecia",
      "hair restoration",
      "hair regrowth",
      "scalp vitality",
    ],
  },

  treatmentPatterns: {
    regenerative_aesthetics: [
      "regenerative aesthetics",
      "regenerative esthetics",
      "regenerative skin",
      "regenerative skincare",
      "collagen regeneration",
      "collagen stimulation",
      "tissue regeneration",
      "biostimulation",
      "biostimulator",
      "exosomes",
      "exosome",
      "stem cell facial",
      "stem cell skincare",
      "growth factors",
      "prp facial",
      "prf facial",
      "pdrn",
      "polynucleotides",
      "polynucleotide",
      "rejuran",
      "juvelook",
      "profhilo",
      "skinvive",
      "sculptra",
      "radiesse",
      "skin booster",
      "skin boosters",
    ],
    injectables: [
      "botox",
      "tox",
      "neurotoxin",
      "dysport",
      "xeomin",
      "jeuveau",
      "filler",
      "fillers",
      "dermal filler",
      "hyaluronic acid filler",
      "injectables",
      "biostimulator injections",
    ],
    devices_energy: [
      "laser",
      "lasers",
      "ipl",
      "bbl",
      "radiofrequency",
      "rf microneedling",
      "microneedling",
      "morpheus8",
      "ultherapy",
      "thermage",
      "co2 laser",
      "fractional laser",
      "fraxel",
      "sofwave",
      "hifu",
      "led",
      "red light therapy",
    ],
    procedures_skin: [
      "chemical peel",
      "peels",
      "facial",
      "hydrafacial",
      "skin booster",
      "skin boosters",
      "mesotherapy",
      "dermaplaning",
      "microdermabrasion",
      "exosome facial",
      "vampire facial",
    ],
    surgery: [
      "facelift",
      "neck lift",
      "blepharoplasty",
      "plastic surgery",
      "cosmetic surgery",
      "surgical",
    ],
    skincare_topicals: [
      "serum",
      "toner",
      "moisturizer",
      "cream",
      "ampoule",
      "retinol",
      "retinal",
      "tranexamic acid",
      "azelaic acid",
      "bakuchiol",
      "peptides",
      "collagen skincare",
      "pdrn skincare",
      "exosome serum",
    ],
  },

  burdenTerms: [
    "confused",
    "confusing",
    "skeptical",
    "skepticism",
    "scam",
    "overhyped",
    "hype",
    "unsafe",
    "safety",
    "risk",
    "side effects",
    "downtime",
    "recovery",
    "expensive",
    "cost",
    "price",
    "worth it",
    "results",
    "visible results",
    "clinical results",
    "before and after",
    "natural results",
    "subtle results",
    "not overfilled",
    "long lasting",
    "longevity",
    "maintenance",
    "trust",
    "credible",
    "provider",
    "doctor",
    "dermatologist",
    "plastic surgeon",
    "injector",
    "med spa",
    "aesthetic clinic",
    "skin clinic",
    "consumer education",
    "education",
    "awareness",
    "interest",
    "demand",
    "trend",
    "trending",
    "market",
    "opportunity",
    "white space",
    "innovation",
    "science-backed",
    "clinically proven",
    "clinic-level",
    "professional-grade",
  ],

  patientIndicators: [
    "i tried",
    "i got",
    "i had",
    "i want",
    "i'm interested",
    "i am interested",
    "i'm considering",
    "i am considering",
    "my skin",
    "my face",
    "my wrinkles",
    "my hair",
    "my results",
    "before and after",
    "worth it for me",
    "i love",
    "why i love",
    "my routine",
    "my skincare routine",
    "game changer",
    "must-have",
    "must have",
    "i’ve been loving",
    "i've been loving",
  ],

  caregiverIndicators: [
    "my client",
    "my patient",
    "our patients",
    "our clients",
    "patients ask",
    "clients ask",
    "as a provider",
    "as an injector",
    "as a dermatologist",
    "as a plastic surgeon",
    "as an aesthetician",
    "as an esthetician",
    "in my clinic",
    "in our clinic",
    "at our med spa",
    "our practice",
    "our aesthetic practice",
    "provider education",
    "patient education",
  ],

  educationalExclusionPatterns: [
    "register for our webinar",
    "join our webinar",
    "limited time offer",
    "book now",
    "call today",
    "link in bio",
    "promo code",
    "giveaway",
    "enroll now",
    "free consultation",
    "price list",
    "course fee",
    "training academy",
    "fellowship in advanced aesthetic medicine",
  ],

  lowQualityNoisePatterns: [
    "spam",
    "crypto",
    "forex",
    "onlyfans",
    "weight loss miracle",
    "miracle cure",
    "copy and paste",
    "dm me",
    "affiliate link",
    "anonymous via throne",
    "withheld in this country",
    "legal demand",
    "copyright",
  ],

  hardExclusionPatterns: [
    "stock is up",
    "stock is down",
    "earnings call",
    "investor presentation",
    "share price",
    "bullish",
    "bearish",
    "nasdaq",
    "globe newswire",
    "businesswire",
    "pr newswire",
    "clinical-stage biotechnology company",
    "clinical stage biotechnology company",
    "clinical-stage company",
    "clinical stage company",
    "biologics license application",
    "clinicaltrials.gov",
    "phase 1",
    "phase i",
    "phase 2",
    "phase ii",
    "phase 3",
    "phase iii",
    "pipeline assessment",
    "drug pipeline",
    "investor",
    "shareholder",
    "securities",
    "forward-looking statements",
    "form 10-k",
    "form 8-k",
  ],

  extraExclusionPatterns: [
    "regenerative agriculture",
    "regenerative farming",
    "soil regeneration",
    "regenerative braking",
    "regenerative tourism",
    "regenerative design",
    "regenerative finance",

    "knee pain",
    "knee injury",
    "meniscus",
    "meniscal",
    "uclid injury",
    "ucl injury",
    "baseball athletes",
    "orthopedic",
    "orthopaedic",
    "sports medicine",
    "rotator cuff",
    "tendon injury",
    "arthritis knee",
    "osteoarthritis",
    "joint pain",
    "back pain",
    "sciatica",
    "urology",
    "erectile dysfunction",
    "ed treatment",
    "penile",
    "ovarian rejuvenation",
    "fertility",
    "endometrial",
    "donor egg",
    "tinnitus",
    "hearing loss",
    "hyperacusis",
    "autism spectrum disorder",
    "duchenne",
    "central nervous system",
    "cns injuries",
    "nerve repair",
    "vision loss",
    "ophthalmology",
    "pre-exposure prophylaxis",
    "hiv prevention",
    "psychiatric rehabilitation",
    "behavioral health",
    "addiction treatment",
    "painreform",
    "ocular",
    "ocuring",
    "clinical drug",
    "pharmaceutical-grade exosomes",
    "mesenchymal stem cells",
    "cell and gene therapy",
    "next-generation sequencing",
    "antibody",
    "bioprocessing",
    "protein purification",
    "engineered materials",
    "composites",
    "ceramics",
  ],

  requirePatientVoice: false,
  requireDiseaseContextForSymptoms: false,
};